/*
 * Appwrite
 *
 * Appwrite backend as a service cuts up to 70% of the time and costs required for building a modern application. We abstract and simplify common development tasks behind a REST APIs, to help you develop your app in a fast and secure way. For full API documentation and tutorials go to [https://appwrite.io/docs](https://appwrite.io/docs)
 *
 * The version of the OpenAPI document: 1.4.9
 * Contact: team@appwrite.io
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct AccountUpdateRecoveryRequest {
    /// User ID.
    #[serde(rename = "userId")]
    pub user_id: String,
    /// Valid reset token.
    #[serde(rename = "secret")]
    pub secret: String,
    /// New user password. Must be at least 8 chars.
    #[serde(rename = "password")]
    pub password: String,
    /// Repeat new user password. Must be at least 8 chars.
    #[serde(rename = "passwordAgain")]
    pub password_again: String,
}

impl AccountUpdateRecoveryRequest {
    pub fn new(user_id: String, secret: String, password: String, password_again: String) -> AccountUpdateRecoveryRequest {
        AccountUpdateRecoveryRequest {
            user_id,
            secret,
            password,
            password_again,
        }
    }
}


