/*
 * Appwrite
 *
 * Appwrite backend as a service cuts up to 70% of the time and costs required for building a modern application. We abstract and simplify common development tasks behind a REST APIs, to help you develop your app in a fast and secure way. For full API documentation and tutorials go to [https://appwrite.io/docs](https://appwrite.io/docs)
 *
 * The version of the OpenAPI document: 1.4.9
 * Contact: team@appwrite.io
 * Generated by: https://openapi-generator.tech
 */

/// AttributeList : Attributes List



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct AttributeList {
    /// Total number of attributes in the given collection.
    #[serde(rename = "total")]
    pub total: i32,
    /// List of attributes.
    #[serde(rename = "attributes")]
    pub attributes: Vec<serde_json::Value>,
}

impl AttributeList {
    /// Attributes List
    pub fn new(total: i32, attributes: Vec<serde_json::Value>) -> AttributeList {
        AttributeList {
            total,
            attributes,
        }
    }
}


