/*
 * Appwrite
 *
 * Appwrite backend as a service cuts up to 70% of the time and costs required for building a modern application. We abstract and simplify common development tasks behind a REST APIs, to help you develop your app in a fast and secure way. For full API documentation and tutorials go to [https://appwrite.io/docs](https://appwrite.io/docs)
 *
 * The version of the OpenAPI document: 1.4.9
 * Contact: team@appwrite.io
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct DatabasesUpdateRelationshipAttributeRequest {
    /// Constraints option
    #[serde(rename = "onDelete", skip_serializing_if = "Option::is_none")]
    pub on_delete: Option<OnDelete>,
}

impl DatabasesUpdateRelationshipAttributeRequest {
    pub fn new() -> DatabasesUpdateRelationshipAttributeRequest {
        DatabasesUpdateRelationshipAttributeRequest {
            on_delete: None,
        }
    }
}

/// Constraints option
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum OnDelete {
    #[serde(rename = "cascade")]
    Cascade,
    #[serde(rename = "restrict")]
    Restrict,
    #[serde(rename = "setNull")]
    SetNull,
}

impl Default for OnDelete {
    fn default() -> OnDelete {
        Self::Cascade
    }
}

