/*
 * Appwrite
 *
 * Appwrite backend as a service cuts up to 70% of the time and costs required for building a modern application. We abstract and simplify common development tasks behind a REST APIs, to help you develop your app in a fast and secure way. For full API documentation and tutorials go to [https://appwrite.io/docs](https://appwrite.io/docs)
 *
 * The version of the OpenAPI document: 1.4.9
 * Contact: team@appwrite.io
 * Generated by: https://openapi-generator.tech
 */

/// File : File



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct File {
    /// File ID.
    #[serde(rename = "$id")]
    pub dollar_id: String,
    /// Bucket ID.
    #[serde(rename = "bucketId")]
    pub bucket_id: String,
    /// File creation date in ISO 8601 format.
    #[serde(rename = "$createdAt")]
    pub dollar_created_at: String,
    /// File update date in ISO 8601 format.
    #[serde(rename = "$updatedAt")]
    pub dollar_updated_at: String,
    /// File permissions. [Learn more about permissions](https://appwrite.io/docs/permissions).
    #[serde(rename = "$permissions")]
    pub dollar_permissions: Vec<String>,
    /// File name.
    #[serde(rename = "name")]
    pub name: String,
    /// File MD5 signature.
    #[serde(rename = "signature")]
    pub signature: String,
    /// File mime type.
    #[serde(rename = "mimeType")]
    pub mime_type: String,
    /// File original size in bytes.
    #[serde(rename = "sizeOriginal")]
    pub size_original: i32,
    /// Total number of chunks available
    #[serde(rename = "chunksTotal")]
    pub chunks_total: i32,
    /// Total number of chunks uploaded
    #[serde(rename = "chunksUploaded")]
    pub chunks_uploaded: i32,
}

impl File {
    /// File
    pub fn new(dollar_id: String, bucket_id: String, dollar_created_at: String, dollar_updated_at: String, dollar_permissions: Vec<String>, name: String, signature: String, mime_type: String, size_original: i32, chunks_total: i32, chunks_uploaded: i32) -> File {
        File {
            dollar_id,
            bucket_id,
            dollar_created_at,
            dollar_updated_at,
            dollar_permissions,
            name,
            signature,
            mime_type,
            size_original,
            chunks_total,
            chunks_uploaded,
        }
    }
}


