/*
 * Appwrite
 *
 * Appwrite backend as a service cuts up to 70% of the time and costs required for building a modern application. We abstract and simplify common development tasks behind a REST APIs, to help you develop your app in a fast and secure way. For full API documentation and tutorials go to [https://appwrite.io/docs](https://appwrite.io/docs)
 *
 * The version of the OpenAPI document: 1.4.9
 * Contact: team@appwrite.io
 * Generated by: https://openapi-generator.tech
 */

/// Identity : Identity



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct Identity {
    /// Identity ID.
    #[serde(rename = "$id")]
    pub dollar_id: String,
    /// Identity creation date in ISO 8601 format.
    #[serde(rename = "$createdAt")]
    pub dollar_created_at: String,
    /// Identity update date in ISO 8601 format.
    #[serde(rename = "$updatedAt")]
    pub dollar_updated_at: String,
    /// User ID.
    #[serde(rename = "userId")]
    pub user_id: String,
    /// Identity Provider.
    #[serde(rename = "provider")]
    pub provider: String,
    /// ID of the User in the Identity Provider.
    #[serde(rename = "providerUid")]
    pub provider_uid: String,
    /// Email of the User in the Identity Provider.
    #[serde(rename = "providerEmail")]
    pub provider_email: String,
    /// Identity Provider Access Token.
    #[serde(rename = "providerAccessToken")]
    pub provider_access_token: String,
    /// The date of when the access token expires in ISO 8601 format.
    #[serde(rename = "providerAccessTokenExpiry")]
    pub provider_access_token_expiry: String,
    /// Identity Provider Refresh Token.
    #[serde(rename = "providerRefreshToken")]
    pub provider_refresh_token: String,
}

impl Identity {
    /// Identity
    pub fn new(dollar_id: String, dollar_created_at: String, dollar_updated_at: String, user_id: String, provider: String, provider_uid: String, provider_email: String, provider_access_token: String, provider_access_token_expiry: String, provider_refresh_token: String) -> Identity {
        Identity {
            dollar_id,
            dollar_created_at,
            dollar_updated_at,
            user_id,
            provider,
            provider_uid,
            provider_email,
            provider_access_token,
            provider_access_token_expiry,
            provider_refresh_token,
        }
    }
}


