/*
 * Appwrite
 *
 * Appwrite backend as a service cuts up to 70% of the time and costs required for building a modern application. We abstract and simplify common development tasks behind a REST APIs, to help you develop your app in a fast and secure way. For full API documentation and tutorials go to [https://appwrite.io/docs](https://appwrite.io/docs)
 *
 * The version of the OpenAPI document: 1.4.9
 * Contact: team@appwrite.io
 * Generated by: https://openapi-generator.tech
 */

/// Language : Language



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct Language {
    /// Language name.
    #[serde(rename = "name")]
    pub name: String,
    /// Language two-character ISO 639-1 codes.
    #[serde(rename = "code")]
    pub code: String,
    /// Language native name.
    #[serde(rename = "nativeName")]
    pub native_name: String,
}

impl Language {
    /// Language
    pub fn new(name: String, code: String, native_name: String) -> Language {
        Language {
            name,
            code,
            native_name,
        }
    }
}


