/*
 * Appwrite
 *
 * Appwrite backend as a service cuts up to 70% of the time and costs required for building a modern application. We abstract and simplify common development tasks behind a REST APIs, to help you develop your app in a fast and secure way. For full API documentation and tutorials go to [https://appwrite.io/docs](https://appwrite.io/docs)
 *
 * The version of the OpenAPI document: 1.4.9
 * Contact: team@appwrite.io
 * Generated by: https://openapi-generator.tech
 */

/// Membership : Membership



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct Membership {
    /// Membership ID.
    #[serde(rename = "$id")]
    pub dollar_id: String,
    /// Membership creation date in ISO 8601 format.
    #[serde(rename = "$createdAt")]
    pub dollar_created_at: String,
    /// Membership update date in ISO 8601 format.
    #[serde(rename = "$updatedAt")]
    pub dollar_updated_at: String,
    /// User ID.
    #[serde(rename = "userId")]
    pub user_id: String,
    /// User name.
    #[serde(rename = "userName")]
    pub user_name: String,
    /// User email address.
    #[serde(rename = "userEmail")]
    pub user_email: String,
    /// Team ID.
    #[serde(rename = "teamId")]
    pub team_id: String,
    /// Team name.
    #[serde(rename = "teamName")]
    pub team_name: String,
    /// Date, the user has been invited to join the team in ISO 8601 format.
    #[serde(rename = "invited")]
    pub invited: String,
    /// Date, the user has accepted the invitation to join the team in ISO 8601 format.
    #[serde(rename = "joined")]
    pub joined: String,
    /// User confirmation status, true if the user has joined the team or false otherwise.
    #[serde(rename = "confirm")]
    pub confirm: bool,
    /// User list of roles
    #[serde(rename = "roles")]
    pub roles: Vec<String>,
}

impl Membership {
    /// Membership
    pub fn new(dollar_id: String, dollar_created_at: String, dollar_updated_at: String, user_id: String, user_name: String, user_email: String, team_id: String, team_name: String, invited: String, joined: String, confirm: bool, roles: Vec<String>) -> Membership {
        Membership {
            dollar_id,
            dollar_created_at,
            dollar_updated_at,
            user_id,
            user_name,
            user_email,
            team_id,
            team_name,
            invited,
            joined,
            confirm,
            roles,
        }
    }
}


