/*
 * Appwrite
 *
 * Appwrite backend as a service cuts up to 70% of the time and costs required for building a modern application. We abstract and simplify common development tasks behind a REST APIs, to help you develop your app in a fast and secure way. For full API documentation and tutorials go to [https://appwrite.io/docs](https://appwrite.io/docs)
 *
 * The version of the OpenAPI document: 1.4.9
 * Contact: team@appwrite.io
 * Generated by: https://openapi-generator.tech
 */

/// Phone : Phone



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct Phone {
    /// Phone code.
    #[serde(rename = "code")]
    pub code: String,
    /// Country two-character ISO 3166-1 alpha code.
    #[serde(rename = "countryCode")]
    pub country_code: String,
    /// Country name.
    #[serde(rename = "countryName")]
    pub country_name: String,
}

impl Phone {
    /// Phone
    pub fn new(code: String, country_code: String, country_name: String) -> Phone {
        Phone {
            code,
            country_code,
            country_name,
        }
    }
}


