/*
 * Appwrite
 *
 * Appwrite backend as a service cuts up to 70% of the time and costs required for building a modern application. We abstract and simplify common development tasks behind a REST APIs, to help you develop your app in a fast and secure way. For full API documentation and tutorials go to [https://appwrite.io/docs](https://appwrite.io/docs)
 *
 * The version of the OpenAPI document: 1.4.9
 * Contact: team@appwrite.io
 * Generated by: https://openapi-generator.tech
 */

/// Runtime : Runtime



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct Runtime {
    /// Runtime ID.
    #[serde(rename = "$id")]
    pub dollar_id: String,
    /// Runtime Name.
    #[serde(rename = "name")]
    pub name: String,
    /// Runtime version.
    #[serde(rename = "version")]
    pub version: String,
    /// Base Docker image used to build the runtime.
    #[serde(rename = "base")]
    pub base: String,
    /// Image name of Docker Hub.
    #[serde(rename = "image")]
    pub image: String,
    /// Name of the logo image.
    #[serde(rename = "logo")]
    pub logo: String,
    /// List of supported architectures.
    #[serde(rename = "supports")]
    pub supports: Vec<String>,
}

impl Runtime {
    /// Runtime
    pub fn new(dollar_id: String, name: String, version: String, base: String, image: String, logo: String, supports: Vec<String>) -> Runtime {
        Runtime {
            dollar_id,
            name,
            version,
            base,
            image,
            logo,
            supports,
        }
    }
}


