/*
 * Appwrite
 *
 * Appwrite backend as a service cuts up to 70% of the time and costs required for building a modern application. We abstract and simplify common development tasks behind a REST APIs, to help you develop your app in a fast and secure way. For full API documentation and tutorials go to [https://appwrite.io/docs](https://appwrite.io/docs)
 *
 * The version of the OpenAPI document: 1.4.9
 * Contact: team@appwrite.io
 * Generated by: https://openapi-generator.tech
 */

/// Team : Team



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct Team {
    /// Team ID.
    #[serde(rename = "$id")]
    pub dollar_id: String,
    /// Team creation date in ISO 8601 format.
    #[serde(rename = "$createdAt")]
    pub dollar_created_at: String,
    /// Team update date in ISO 8601 format.
    #[serde(rename = "$updatedAt")]
    pub dollar_updated_at: String,
    /// Team name.
    #[serde(rename = "name")]
    pub name: String,
    /// Total number of team members.
    #[serde(rename = "total")]
    pub total: i32,
    /// Team preferences as a key-value object
    #[serde(rename = "prefs")]
    pub prefs: serde_json::Value,
}

impl Team {
    /// Team
    pub fn new(dollar_id: String, dollar_created_at: String, dollar_updated_at: String, name: String, total: i32, prefs: serde_json::Value) -> Team {
        Team {
            dollar_id,
            dollar_created_at,
            dollar_updated_at,
            name,
            total,
            prefs,
        }
    }
}


