/*
 * Appwrite
 *
 * Appwrite backend as a service cuts up to 70% of the time and costs required for building a modern application. We abstract and simplify common development tasks behind a REST APIs, to help you develop your app in a fast and secure way. For full API documentation and tutorials go to [https://appwrite.io/docs](https://appwrite.io/docs)
 *
 * The version of the OpenAPI document: 1.4.9
 * Contact: team@appwrite.io
 * Generated by: https://openapi-generator.tech
 */

/// Token : Token



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct Token {
    /// Token ID.
    #[serde(rename = "$id")]
    pub dollar_id: String,
    /// Token creation date in ISO 8601 format.
    #[serde(rename = "$createdAt")]
    pub dollar_created_at: String,
    /// User ID.
    #[serde(rename = "userId")]
    pub user_id: String,
    /// Token secret key. This will return an empty string unless the response is returned using an API key or as part of a webhook payload.
    #[serde(rename = "secret")]
    pub secret: String,
    /// Token expiration date in ISO 8601 format.
    #[serde(rename = "expire")]
    pub expire: String,
}

impl Token {
    /// Token
    pub fn new(dollar_id: String, dollar_created_at: String, user_id: String, secret: String, expire: String) -> Token {
        Token {
            dollar_id,
            dollar_created_at,
            user_id,
            secret,
            expire,
        }
    }
}


